Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '004' , '006' , 'R.72' , 'LOTE 12' , 'LOTE 05' , 'LOTE 7' ,     235.86 ,       0.00 , 'V' , '11,50' , '11,50' , '23,00' , '23,00' ,     108.00);                                                                                                                    
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '006' , '008' , 'R.74' , 'LOTE 9' , 'LOTE 7' , 'ENG CEDRO' ,     364.40 ,       0.00 , 'V' , '23,34' , '11,30' , '20,00' , '23,34' ,     108.00);                                                                                                                   
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '008' , '009' , 'R.76' , 'LOTE 19' , 'LOTE 8' , 'LOTE 10' ,     200.00 ,       0.00 , 'V' , '10,00' , '10,00' , '20,00' , '20,00' ,     108.00);                                                                                                                    
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '009' , '014' , 'R.76' , 'LOTE 11' , 'LOTE 13' , 'LOTE 15' ,     200.00 ,       0.00 , 'V' , '10,00' , '10,00' , '20,00' , '20,00' ,     108.00);                                                                                                                   
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '010' , '022' , 'AVENIDA 3' , 'LOTE 30' , 'LOTE 23' , 'LOTE 21' ,     200.00 ,       0.00 , 'V' , '10,00' , '10,00' , '20,00' , '20,00' ,     108.00);                                                                                                              
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '015' , '001' , 'R.64' , 'LOTE 15,16' , 'LOTE 2' , 'ZV-1' ,     200.00 ,       0.00 , 'L' , '10,00' , '10,00' , '20,00' , '20,00' ,     150.00);                                                                                                                    
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '015' , '002' , 'R.64' , 'LOTE 14,15' , 'LOTE 3' , 'LOTE 1' ,     200.00 ,       0.00 , 'L' , '10,00' , '10,00' , '20,00' , '20,00' ,     150.00);                                                                                                                  
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '015' , '003' , 'R.64' , 'LOTE 13,14' , 'LOTE 4' , 'LOTE 2' ,     200.00 ,       0.00 , 'L' , '10,00' , '10,00' , '20,00' , '20,00' ,     150.00);                                                                                                                  
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '015' , '004' , 'R.64' , 'LOTE 12,13' , 'LOTE 5' , 'LOTE 3' ,     200.00 ,       0.00 , 'L' , '10,00' , '10,00' , '20,00' , '20,00' ,     150.00);                                                                                                                  
Insert into Lote (Nu_Lotm , Nu_Quadra , Nu_Lote , Ds_Conf_Frente , Ds_Conf_Fundo , Ds_Conf_Direita , Ds_Conf_Esquerda , Nu_Area , Nu_Dist_Esquina , Situacao , Ds_Dim_Frente , Ds_Dim_Fundo , Ds_Dim_Direita , Ds_Dim_Esquerda , ValorM2 )
          values ('001' , '015' , '005' , 'R.64' , 'LOTE 11,12' , 'LOTE 6' , 'LOTE 4' ,     200.00 ,       0.00 , 'L' , '10,00' , '10,00' , '20,00' , '20,00' ,     150.00);                                                                                                                  